import { GameElementSpecificationsInterface } from 'src/game/interfaces/game-element-specifications-interface';
import { GameFontStylesString, AlingString, ColorsString, textFontSize } from 'src/game/strings/font-styles';
import { gameSceneScale, globalCloseButtonSpecifications } from 'src/game/strings/global-elements/game-elements-specifications';

export const settingsMenuElementsSpecifications: GameElementSpecificationsInterface[] = [
    {
        type: 'image',
        element: 'background',
        assetName: 'modal-scene-background',
        name: 'scene-backgroud',
        scale: gameSceneScale
    },
    {
        type: 'image',
        element: 'background',
        assetName: 'panel-card-background',
        name: 'settings-menu-backgroud',
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 1066,
            objectHeight: 600,
            objectPositionX: 683,
            objectPositionY: 384
        },
    },
    globalCloseButtonSpecifications,
    {
        type: 'text',
        element: 'title',
        name: 'scene-title',
        content: 'AJUSTES DEL JUEGO',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.RED_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Big.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 720,
            objectHeight: 70,
            objectPositionX: 683,
            objectPositionY: 154,
        },
    },
    {
        type: 'text',
        element: 'title',
        name: 'sound-title',
        content: 'SONIDO DEL JUEGO',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_PURPLE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Regular.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 720,
            objectHeight: 60,
            objectPositionX: 683,
            objectPositionY: 241,
        },
    },
    {
        type: 'image',
        element: 'icon',
        assetName: 'on-switch-icon-background',
        name: 'sound-switch',
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 200,
            objectHeight: 70,
            objectPositionX: 668,
            objectPositionY: 340,
        },
    },
    {
        type: 'text',
        element: 'label',
        name: 'off-sound-title',
        content: 'APAGADO',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.LIGHT_PURPLE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Medium.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 170,
            objectHeight: 50,
            objectPositionX: 475,
            objectPositionY: 340,
        },
    },
    {
        type: 'text',
        element: 'label',
        name: 'on-sound-title',
        content: 'ENCENDIDO',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.LIGHT_PURPLE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Medium.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 170,
            objectHeight: 50,
            objectPositionX: 885,
            objectPositionY: 340,
        },
    },
    {
        type: 'text',
        element: 'title',
        name: 'gamepad-title',
        content: 'CONTROL DEL MUNDO VIRTUAL',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_PURPLE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Regular.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 720,
            objectHeight: 60,
            objectPositionX: 683,
            objectPositionY: 445,
        },
    },
    {
        type: 'image',
        element: 'icon',
        assetName: 'check-icon-background',
        name: 'keyboard-check',
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 100,
            objectHeight: 70,
            objectPositionX: 416,
            objectPositionY: 530,
        },
    },
    {
        type: 'image',
        element: 'icon',
        assetName: 'blank-check-icon-background',
        name: 'gamepad-check',
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 100,
            objectHeight: 70,
            objectPositionX: 944,
            objectPositionY: 530,
        },
    },
    {
        type: 'text',
        element: 'label',
        name: 'keyboard-subtitle',
        content: 'TECLADO Y MOUSE',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.LIGHT_PURPLE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Medium.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 400,
            objectHeight: 50,
            objectPositionX: 416,
            objectPositionY: 592,
        },
    },
    {
        type: 'text',
        element: 'label',
        name: 'gamepad-subtitle',
        content: 'MANDO EN PANTALLA',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.LIGHT_PURPLE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Medium.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 400,
            objectHeight: 50,
            objectPositionX: 944,
            objectPositionY: 592,
        },
    },
    {
        type: 'interactiveObject',
        element: 'simple-button',
        assetName: 'continue-button-background',
        name: 'save-settings-button',
        content: 'GUARDAR AJUSTES',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.GREEN_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Medium.fontSize
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 410,
            objectHeight: 75,
            objectPositionX: 683,
            objectPositionY: 684,
        }
    }
]