import { GameElementSpecificationsInterface } from 'src/game/interfaces/game-element-specifications-interface';
import { globalTotalScoreSpecifications, iconButtonScale, globalAssistantSpecifications, globalSettingsButtonSpecifications, globalHomeButtonSpecifications, globalGameElementsName, globalInventoryButtonSpecifications } from 'src/game/strings/global-elements/game-elements-specifications';
import { GameFontStylesString, ColorsString, AlingString, textFontSize } from 'src/game/strings/font-styles';

export const virtualWorldSceneElementsSpecifications: GameElementSpecificationsInterface[] = [
    {
        type: 'image',
        element: 'background',
        assetName: 'minimap-card-background',
        name: 'minimap-border',
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 400,
            objectHeight: 150,
            objectPositionX: 683,
            objectPositionY: 640,
        },
    },
    {
        type: 'text',
        element: 'title',
        name: 'minimap-name',
        content: 'MINIMAPA DE LA ZONA',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.BLACK_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            stroke: ColorsString.WHITE_HEXADECIMAL_STRING,
            strokeThickness: textFontSize.Small.strokeThickness,
            fontSize: textFontSize.Small.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 400,
            objectHeight: 35,
            objectPositionX: 683,
            objectPositionY: 725,
        }
    },
    globalHomeButtonSpecifications,
    {
        type: 'interactiveObject',
        element: 'bottom-title-button',
        assetName: 'world-icon-background',
        name: globalGameElementsName.RETURN_BUTTON,
        content: 'MAPA ZONA',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.BLACK_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            stroke: ColorsString.WHITE_HEXADECIMAL_STRING,
            strokeThickness: textFontSize.Small.strokeThickness,
            fontSize: textFontSize.Small.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 115,
            objectPositionX: 245,
            objectPositionY: 93,
        }
    },
    {
        type: 'text',
        element: 'title',
        name: 'title-name',
        content: 'ZONA\nADMINISTRATIVA',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.RED_HEXADECIMAL_STRING,
            align: AlingString.JUSTIFY_STRING,
            fontSize: textFontSize.Regular.fontSize,
            strokeThickness: textFontSize.Regular.strokeThickness,
            stroke: ColorsString.WHITE_HEXADECIMAL_STRING
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 700,
            objectHeight: 60,
            objectPositionX: 340,
            objectPositionY: 35,
        },
        originX: 0,
        originY: 0
    },
    {
        type: 'interactiveObject',
        element: 'button',
        assetName: 'up-button-background',
        name: 'up-button',
        content: '',
        style: {
            fontSize: '16px',
            fontFamily: 'Segoe UI Emoji',
            color: '#087CF5',
            align: 'center',
            stroke: '#076BD3',
            strokeThickness: 1,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 105,
            objectHeight: 100,
            objectPositionX: 214,
            objectPositionY: 577,
        },
    },
    {
        type: 'interactiveObject',
        element: 'button',
        assetName: 'down-button-background',
        name: 'down-button',
        content: '',
        style: {
            fontSize: '16px',
            fontFamily: 'Segoe UI Emoji',
            color: '#087CF5',
            align: 'center',
            stroke: '#076BD3',
            strokeThickness: 1,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 105,
            objectHeight: 100,
            objectPositionX: 214,
            objectPositionY: 686,
        },
    },
    {
        type: 'interactiveObject',
        element: 'button',
        assetName: 'left-button-background',
        name: 'left-button',
        content: '',
        style: {
            fontSize: '16px',
            fontFamily: 'Segoe UI Emoji',
            color: '#087CF5',
            align: 'center',
            stroke: '#076BD3',
            strokeThickness: 1,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 105,
            objectHeight: 100,
            objectPositionX: 100,
            objectPositionY: 686,
        },
    },
    {
        type: 'interactiveObject',
        element: 'button',
        assetName: 'right-button-background',
        name: 'right-button',
        content: '',
        style: {
            fontSize: '16px',
            fontFamily: 'Segoe UI Emoji',
            color: '#087CF5',
            align: 'center',
            stroke: '#076BD3',
            strokeThickness: 1,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 105,
            objectHeight: 100,
            objectPositionX: 328,
            objectPositionY: 686,
        },
    },
    globalTotalScoreSpecifications,
    globalAssistantSpecifications,
    globalInventoryButtonSpecifications,
    {
        type: 'interactiveObject',
        element: 'bottom-title-button',
        assetName: 'enable-gamepad-button-background',
        name: 'activate-gamepad-button',
        content: 'MANDO',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.BLACK_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            stroke: ColorsString.WHITE_HEXADECIMAL_STRING,
            strokeThickness: textFontSize.Small.strokeThickness,
            fontSize: textFontSize.Small.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: iconButtonScale.objectWidth,
            objectHeight: iconButtonScale.objectHeight,
            objectPositionX: 1258,
            objectPositionY: 502,
        },
    },
    globalSettingsButtonSpecifications,
    {
        type: 'interactiveObject',
        element: 'bottom-title-button',
        assetName: 'enter-icon-background',
        name: 'enter-button',
        content: 'ENTRAR',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.BLACK_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            stroke: ColorsString.WHITE_HEXADECIMAL_STRING,
            strokeThickness: textFontSize.Small.strokeThickness,
            fontSize: textFontSize.Small.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: iconButtonScale.objectWidth,
            objectHeight: iconButtonScale.objectHeight,
            objectPositionX: 1119,
            objectPositionY: 654,
        },
    }
]
