import { GameElementSpecificationsInterface } from 'src/game/interfaces/game-element-specifications-interface';
import { gameSceneScale, baseSceneBackground } from 'src/game/strings/global-elements/game-elements-specifications';
import { GameFontStylesString, ColorsString, AlingString, textFontSize } from 'src/game/strings/font-styles';

export const loadSceneElementsSpecifications: GameElementSpecificationsInterface[] = [
    baseSceneBackground,
    {
        type: 'image',
        element: 'illustration',
        assetName: 'load-assistant-background',
        name: 'load-assistant-background',
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 414,
            objectHeight: 424,
            objectPositionX: 260,
            objectPositionY: 362,
        },
    },
    {
        type: 'text',
        element: 'title',
        name: 'title',
        content: 'Sabías que...',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_RED_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            stroke: ColorsString.WHITE_HEXADECIMAL_STRING,
            strokeThickness: 25,
            fontSize: '60px'
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 460,
            objectHeight: 72,
            objectPositionX: 55,
            objectPositionY: 40,
        },
        originX: 0,
        originY: 0,
    },
    {
        type: 'image',
        element: 'illustration',
        assetName: 'feedback-card-background',
        name: 'feedback-background',
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 816,
            objectHeight: 450,
            objectPositionX: 904,
            objectPositionY: 290,
        },
    },
    {
        type: 'interactiveObject',
        element: 'button',
        assetName: 'feedback-title-card-background',
        name: 'feedback-title',
        content: 'VISIÓN',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_PURPLE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Big.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 690,
            objectHeight: 90,
            objectPositionX: 904,
            objectPositionY: 160,
        },
    },
    {
        type: 'text',
        element: 'feedback',
        name: 'feedback',
        content: 'Usar nuestra ilimitada pasión por la tecnología, para otorgar emoción y entretenimiento innovador.',
        style: {
            fontFamily: GameFontStylesString.SMALL_FONT,
            color: ColorsString.PURPLE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            stroke: ColorsString.PURPLE_HEXADECIMAL_STRING,
            strokeThickness: 1,
            fontSize: '45px',
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 750,
            objectHeight: 255,
            objectPositionX: 904,
            objectPositionY: 355,
        },
    },
    {
        type: 'image',
        element: 'background',
        assetName: 'load-feedback-card-background',
        name: 'load-feedback-background',
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 1260,
            objectHeight: 167,
            objectPositionX: 683,
            objectPositionY: 640,
        },
    },
    {
        type: 'text',
        element: 'load-feedback',
        name: 'load-feedback',
        content: 'Dentro de la empresa existe un claro objetivo que es: otorgar emoción e innovación con cada producto',
        style: {
            fontFamily: GameFontStylesString.SMALL_FONT,
            color: ColorsString.DARK_BLUE_HEXADECIMAL_STRING,
            align: AlingString.JUSTIFY_STRING,
            stroke: ColorsString.DARK_BLUE_HEXADECIMAL_STRING,
            strokeThickness: 2,
            fontSize: textFontSize.Regular.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 890,
            objectHeight: 100,
            objectPositionX: 531,
            objectPositionY: 639,
        },
    },
    {
        type: 'text',
        element: 'load-text',
        name: 'load-text',
        content: 'CARGANDO...',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.RED_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Regular.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 284,
            objectHeight: 50,
            objectPositionX: 1127,
            objectPositionY: 639,
        },
    },
    {
        type: 'interactiveObject',
        element: 'simple-button',
        assetName: 'sign-out-button-background',
        name: 'load-continue-button',
        content: 'CONTINUAR',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.RED_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Medium.fontSize
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 300,
            objectHeight: 75,
            objectPositionX: 1127,
            objectPositionY: 639,
        },
    },
]